//
//  iTrace
//
//  Created by Fabrizio Pezzola on 11/02/2020.
//  Copyright © 2020 Fabrizio Pezzola. All rights reserved.
//

protocol Tesselatable: RenderObject {
    // tesselate this object into a {@link PrimitiveList}. This may return
    // null if tesselation fails.
    //
    // @return a list of primitives generated by the tesselation
    func tesselate() -> PrimitiveList?

    // Compute a bounding box of this object in world space, using the specified
    // object-to-world transformation matrix. The bounds should be as exact as
    // possible, if they are difficult or expensive to compute exactly, you may
    // use {@link AffineTransform#transform(BoundingBox)}. If the matrix is
    // null no transformation is needed, and object space is
    // equivalent to world space. This method may return null if
    // these bounds are difficult or impossible to compute, in which case the
    // tesselation will be executed right away and the bounds of the resulting
    // primitives will be used.
    //
    // @param o2w object to world transformation matrix
    // @return object bounding box in world space
    func getWorldBounds(_ o2w: AffineTransform?) -> BoundingBox?
}
